trigger:
  - main

pool:
  name: 'Aman-Self-Hosted-CICD'  # Ensure this agent is running as root

variables:
  DOCKER_IMAGE: 'nginx:latest'  # Change to the image you want to scan
  DOCKERHUB_REPO: 'aman267/nginx' # Change to your DockerHub repo
  SCANNED_IMAGE_TAG: 'scanned'
  DOCKER_USERNAME: 'aman267'
  DOCKER_PASSWORD: 'Hanuman26797'  # Use Azure DevOps secret variable

stages:
  - stage: Pull_Image
    displayName: 'Pull Image from Docker Hub'
    jobs:
      - job: PullDockerImage
        displayName: 'Pull Docker Image'
        steps:
          - script: |
              echo "Pulling Docker Image: $(DOCKER_IMAGE)"
              sudo docker pull $(DOCKER_IMAGE)
            displayName: 'Pull Image from Docker Hub'

  - stage: Scan_Image
    displayName: 'Scan Image with Qscanner'
    dependsOn: Pull_Image
    jobs:
      - job: ScanDockerImage
        displayName: 'Scan Image with Qscanner'
        steps:
          - script: |
              echo "Running Qscanner Scan on Image: $(DOCKER_IMAGE)"
              sudo ./root/linux-amd64/qscanner image $(DOCKER_IMAGE) --mode get-report --access-token $QUALYS_ACCESS_TOKEN --pod US2 --report-format table,json 
              cp /root/qualys/qscanner/data/eeb6ee3f44bd0b5103bb561b4c16bcb82328cfe5809ab675bb17ab3a16c517c9-Report.json 
            displayName: 'Scan Image with Qscanner'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Qscanner Scan Report'
            inputs:
              pathToPublish: '/root/qualys/qscanner/data//root/qualys/qscanner/data/eeb6ee3f44bd0b5103bb561b4c16bcb82328cfe5809ab675bb17ab3a16c517c9-Report.json'
              artifactName: 'SecurityReports'
 
          
  - stage: Push_to_DockerHub
    displayName: 'Push Image to Docker Hub'
    dependsOn: Scan_Image
    condition: succeeded()
    jobs:
      - job: PushDockerImage
        displayName: 'Push Scanned Image to Docker Hub'
        steps:
          - script: |
              echo "Logging in to Docker Hub..."
              echo "$(DOCKER_PASSWORD)" | sudo docker login -u "$(DOCKER_USERNAME)" --password-stdin
            displayName: 'Login to Docker Hub'

          - script: |
              echo "Tagging Image for Docker Hub..."
              sudo docker tag $(DOCKER_IMAGE) $(DOCKERHUB_REPO):$(SCANNED_IMAGE_TAG)
            displayName: 'Tag Image for Docker Hub'

          - script: |
              echo "Pushing Image to Docker Hub..."
              sudo docker push $(DOCKERHUB_REPO):$(SCANNED_IMAGE_TAG)
            displayName: 'Push Image to Docker Hub'
